version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-django-app
    ports:
      - 8002:8001
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-network
  
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment: 
      POSTGRES_DB: test
      POSTGRES_USER: sagar
      POSTGRES_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/psql
    container_name: postgres_server_2
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_2
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sagarsinha1803@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

      