# Generated by Django 3.2.8 on 2021-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='userId',
            field=models.IntegerField(default=False, max_length=10),
        ),
    ]
